### ISSUE TITLE
GPU Plugin Instantly Crashing Client whenever turned on.

### ISSUE THREAD

**Issue by Dreamscape123** [runelite/runelite#10659]
**Describe the bug**
Whenever the GPU plugin, with default settings, is turned on the client instantly crashes. This bug is being experienced even from the login screen.

**To Reproduce**
1. Launch RuneLite
2. Turn on GPU plugin
3. Client instantly crashes

**Expected behavior**
When turning on the GPU plugin the client shouldn't be crashing and allowing to increase draw distance.

**Environment (please complete the following information):**
 - OS: Microsoft Windows 10 Home
 - CPU: Intel Core i7-8700
 - GPU: NVIDIA GeForce GTX 1060 6GB

 - RuneLite version: Current

**Additional context**
In the past, I was able to run the GPU plugin at max settings with absolutely no issues. Then within the past 6 months, the plugin just started instantly crashing the client upon turning it on. I have tried all of the workarounds listed in #6523 such as all methods of disabling hardware acceleration, turning off compatibility mode, and optimizing the settings within the NVIDIA Control Panel. All of which were unable to help.

Can any developer confirm if this is an issue on my end or runelite's end? Also if any additional information is required then I can give that.

**Comment by Graviton1647** [comment]
Hey Dreamscape123,
   I have tired this with near enough these specs baring the cpu and seems fine do you have a stack trace of the error in the following location 

`C:\Users\user\.runelite\logs`

Thanks

**Comment by Dreamscape123** [comment]
@Graviton1647 I have combed through both of the client.log and launcher.log files after starting runelite with an instant crash by having a GPU plugin turned on and also starting runelite nominally with the setting off and no crash. It appears that this issue isn't generating an error line in either of those .log files. since each of the entries for the crash and no-crash scenario are exactly the same.

I also do not see that it generated any other type of error log file within that folder.

**Comment by Graviton1647** [comment]
I may have to download VM Machine then so I can look myself I remember when I was working on my game it was a issue and I fixed it just can't remember how

**Comment by Dreamscape123** [comment]
@Graviton1647 thank you for your help in assisting me to solve this issue. I have looked at most all posts on here revolving around GPU issues and tried most all workarounds suggested. None have worked so far.

**Comment by killersloth** [comment]
I recently started having the same issue, also noticing the client is trying to use all 8gb of my VRAM and 5gb+ of system memory at around the same time it happens.  
Besides the 0xc0000005 in jvm crash log, one was EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d), and I'm getting a lot of this in the client log: 
`[Client] ERROR net.runelite.client.RuneLite - Game crash: null
com.jogamp.opengl.GLException: Error swapping buffers
	at jogamp.opengl.windows.wgl.WindowsWGLDrawable.swapBuffersImpl(WindowsWGLDrawable.java:93)
	at jogamp.opengl.GLDrawableImpl.swapBuffers(GLDrawableImpl.java:88)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1121)
	at bj.bf(bj.java:38472)
	at bj.aj(bj.java)
	at bj.run(bj.java:318)
	at java.base/java.lang.Thread.run(Unknown Source)`

Seems related.

**Comment by Brandieee** [comment]
Encountering the same problem.
Testing done on a fresh install of RuneLite with profiles etc. removed from .runelite and simply on login screen

Environment:
- OS: Microsoft Windows 10 Pro Version 1809
-  CPU: Intel Core i5-8250U
-  GPU: iGPU in processor
-  RuneLite version: 1.6.10.1

Attaching logs client, launcher and crash log for normal and HW acceleration forced off:

"Normal": 
[client_normal.log](https://github.com/runelite/runelite/files/4470170/client_normal.log)
[jvm_crash_pid_1976_normal.log](https://github.com/runelite/runelite/files/4470171/jvm_crash_pid_1976_normal.log)
[launcher_normal.log](https://github.com/runelite/runelite/files/4470172/launcher_normal.log)

HW acceleration forced off with ""%localappdata%\RuneLite\RuneLite.exe" --mode=OFF"
[client_hw_acc_off.log](https://github.com/runelite/runelite/files/4470174/client_hw_acc_off.log)
[jvm_crash_pid_11380_hw_acc_off.log](https://github.com/runelite/runelite/files/4470175/jvm_crash_pid_11380_hw_acc_off.log)
[launcherhw_acc_off.log](https://github.com/runelite/runelite/files/4470176/launcherhw_acc_off.log)

**Comment by Brandieee** [comment]
Still experiencing this issue, if anyone is looking into it and wants any additional information just say the word.

**Comment by OuchKick** [comment]
Having the same issue as well

**Comment by Brandieee** [comment]
FWIW last update (1.7.4) seems to have fixed this for me.

**Comment by Nightfirecat** [comment]
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.
