### ISSUE TITLE
macOS Big Sur Compatibility

### ISSUE THREAD

**Issue by chadbdurham** [runelite/runelite#11965]
As a heads up, RuneLite is not compatible with macOS Big Sur. The client will not launch and will make you force close it.

_**I'm aware that this is a developer beta and making this issue for reporting purposes._

**Comment by Broooklyn** [comment]
I've been using macOS 11 and have encountered the same issue when trying to open the release app. It is however possible to open RuneLite via the exec at `RuneLite.app/Contents/MacOS/RuneLite`.  

That said, the issue, I believe, is due to the current inability to install `python@3.8` via homebrew, which is a dependency of `glfw` and/or `glew`.

**Comment by Broooklyn** [comment]
`python@3.8` has been updated, but unfortunately that doesn't seem to have fixed the issue.

**Comment by ungegravy** [comment]
Thanks, that works for big sur!

**Comment by AndrewWCarson** [comment]
Here's a logstream to tsv with 'runelite' as the search parameter when opening Runelite.app on macOS 11.

`error	22:07:37.003796-0700	Finder	LAUNCH: No architectures specified in launch archictectures [ NULL ]  for app=file:///Applications/RuneLite.app which likely is an error.
default	22:07:37.004149-0700	runningboardd	Executing launch request for app<application.net.runelite.launcher.6564800.6564806(501)> (LS launch net.runelite.launcher)
default	22:07:37.004201-0700	runningboardd	Creating and launching job for: app<application.net.runelite.launcher.6564800.6564806(501)>
default	22:07:37.009486-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] This process will not be managed.
default	22:07:37.009515-0700	runningboardd	Now tracking process: [app<application.net.runelite.launcher.6564800.6564806(501)>:7150]
default	22:07:37.009558-0700	runningboardd	Using default underlying assertion for app: [app<application.net.runelite.launcher.6564800.6564806(501)>:7150]
default	22:07:37.009598-0700	runningboardd	Calculated state for app<application.net.runelite.launcher.6564800.6564806(501)>: running-suspended (role: None)
default	22:07:37.009634-0700	runningboardd	Acquiring assertion targeting app<application.net.runelite.launcher.6564800.6564806(501)> from originator [app<application.net.runelite.launcher.6564800.6564806(501)>:7150] with description <RBSAssertionDescriptor	 "RB Underlying Assertion" ID:156-156-20488 target:7150 attributes:[
	<RBSDomainAttribute	 domain:"com.apple.underlying" name:"defaultUnderlyingAppAssertion" sourceEnvironment:"(null)">,
	<RBSAcquisitionCompletionAttribute	 policy:AfterApplication>
	]>
default	22:07:37.009777-0700	runningboardd	Assertion 156-156-20488 (target:app<application.net.runelite.launcher.6564800.6564806(501)>) will be created as active
default	22:07:37.010052-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] reported to RB as running
default	22:07:37.010255-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring jetsam update because this process is not memory-managed
default	22:07:37.010358-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring suspend because this process is not lifecycle managed
default	22:07:37.010453-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Set darwin role to: None
default	22:07:37.010549-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring GPU update because this process is not GPU managed
default	22:07:37.010229-0700	runningboardd	Calculated state for app<application.net.runelite.launcher.6564800.6564806(501)>: running-suspended (role: None)
default	22:07:37.010780-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Skipping AppNap state - not lifecycle managed
default	22:07:37.010904-0700	runningboardd	Finished acquiring assertion 156-156-20488 (target:app<application.net.runelite.launcher.6564800.6564806(501)>)
default	22:07:37.011025-0700	runningboardd	Successfully acquired underlying assertion for [app<application.net.runelite.launcher.6564800.6564806(501)>:7150]
default	22:07:37.011053-0700	runningboardd	Acquiring assertion targeting app<application.net.runelite.launcher.6564800.6564806(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:87] with description <RBSAssertionDescriptor	 "foregroundApp:7150" ID:156-87-20489 target:7150 attributes:[
	<RBSDomainAttribute	 domain:"com.apple.launchservicesd" name:"RoleUserInteractiveNonFocal" sourceEnvironment:"(null)">
	]>
default	22:07:37.011207-0700	runningboardd	Assertion 156-87-20489 (target:app<application.net.runelite.launcher.6564800.6564806(501)>) will be created as active
default	22:07:37.012250-0700	loginwindow	-[PersistentAppsSupport applicationReady:] 	 App: RuneLite, ready, updating active tracking timer
default	22:07:37.012301-0700	loginwindow	-[ApplicationManager checkInAppContext:eventData:] 	 ApplicationManager: Checked in app : RuneLite
default	22:07:37.012454-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring jetsam update because this process is not memory-managed
default	22:07:37.012856-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring suspend because this process is not lifecycle managed
default	22:07:37.012177-0700	runningboardd	Calculated state for app<application.net.runelite.launcher.6564800.6564806(501)>: running-active (role: UserInteractiveNonFocal)
default	22:07:37.013113-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Set darwin role to: UserInteractiveNonFocal
default	22:07:37.013348-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring GPU update because this process is not GPU managed
default	22:07:37.012164-0700	runningboardd	Acquiring assertion targeting app<application.net.runelite.launcher.6564800.6564806(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:87] with description <RBSAssertionDescriptor	 "foregroundApp:7150" ID:156-87-20490 target:7150 attributes:[
	<RBSDomainAttribute	 domain:"com.apple.launchservicesd" name:"RoleUserInteractiveNonFocal" sourceEnvironment:"(null)">
	]>
default	22:07:37.013703-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Skipping AppNap state - not lifecycle managed
default	22:07:37.013665-0700	runningboardd	Assertion 156-87-20490 (target:app<application.net.runelite.launcher.6564800.6564806(501)>) will be created as active
default	22:07:37.014337-0700	runningboardd	Finished acquiring assertion 156-87-20489 (target:app<application.net.runelite.launcher.6564800.6564806(501)>)
default	22:07:37.014887-0700	runningboardd	Invalidating assertion 156-87-20489 (target:app<application.net.runelite.launcher.6564800.6564806(501)>) from originator [daemon<com.apple.coreservices.launchservicesd>:87]
default	22:07:37.015634-0700	runningboardd	Acquiring assertion targeting app<application.net.runelite.launcher.6564800.6564806(501)> from originator [daemon<com.apple.coreservices.appleevents(55)>:386] with description <RBSAssertionDescriptor	 "AE/RuneLite" ID:156-386-20491 target:7150 attributes:[
	<RBSDomainAttribute	 domain:"com.apple.launchservicesd" name:"LSNotification" sourceEnvironment:"(null)">
	]>
default	22:07:37.015822-0700	runningboardd	Assertion 156-386-20491 (target:app<application.net.runelite.launcher.6564800.6564806(501)>) will be created as active
default	22:07:37.016189-0700	runningboardd	Finished acquiring assertion 156-87-20490 (target:app<application.net.runelite.launcher.6564800.6564806(501)>)
default	22:07:37.017113-0700	distnoted	register name: com.apple.sharedfilelist.change object: com.apple.LSSharedFileList.ApplicationRecentDocuments/net.runelite.launcher token: b200000059 pid: 2485
default	22:07:37.016896-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring jetsam update because this process is not memory-managed
default	22:07:37.017076-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring suspend because this process is not lifecycle managed
default	22:07:37.017242-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring GPU update because this process is not GPU managed
default	22:07:37.017575-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Skipping AppNap state - not lifecycle managed
default	22:07:37.017683-0700	runningboardd	Finished acquiring assertion 156-386-20491 (target:app<application.net.runelite.launcher.6564800.6564806(501)>)
default	22:07:37.016809-0700	runningboardd	Calculated state for app<application.net.runelite.launcher.6564800.6564806(501)>: running-active (role: UserInteractiveNonFocal)
error	22:07:37.032203-0700	kernel	Sandbox: logd_helper(118) deny(1) file-read-data /Applications/RuneLite.app/Contents/Resources/jre/lib/jli/libjli.dylib
error	22:07:37.032341-0700	kernel	Sandbox: logd_helper(118) deny(1) file-read-data /Applications/RuneLite.app/Contents/Resources/jre/lib/server/libjvm.dylib
error	22:07:37.032457-0700	kernel	Sandbox: logd_helper(118) deny(1) file-read-data /Applications/RuneLite.app/Contents/Resources/jre/lib/libverify.dylib
error	22:07:37.032577-0700	kernel	Sandbox: logd_helper(118) deny(1) file-read-data /Applications/RuneLite.app/Contents/Resources/jre/lib/libjava.dylib
default	22:07:42.005167-0700	runningboardd	Assertion did invalidate due to timeout: 156-156-20488 (target:app<application.net.runelite.launcher.6564800.6564806(501)>)
default	22:07:42.197915-0700	runningboardd	Calculated state for app<application.net.runelite.launcher.6564800.6564806(501)>: running-active (role: UserInteractiveNonFocal)
default	22:07:42.197958-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring jetsam update because this process is not memory-managed
default	22:07:42.198259-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring suspend because this process is not lifecycle managed
default	22:07:42.198450-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring GPU update because this process is not GPU managed
default	22:07:42.198848-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Skipping AppNap state - not lifecycle managed
default	22:07:42.199126-0700	runningboardd	Assertion did invalidate due to timeout: 156-386-20491 (target:app<application.net.runelite.launcher.6564800.6564806(501)>)
default	22:07:42.397509-0700	runningboardd	Calculated state for app<application.net.runelite.launcher.6564800.6564806(501)>: running-active (role: UserInteractiveNonFocal)
default	22:07:42.397562-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring jetsam update because this process is not memory-managed
default	22:07:42.397633-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring suspend because this process is not lifecycle managed
default	22:07:42.397676-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring GPU update because this process is not GPU managed
default	22:07:42.397907-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Skipping AppNap state - not lifecycle managed
default	22:08:16.420702-0700	runningboardd	Acquiring assertion targeting app<application.net.runelite.launcher.6564800.6564806(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:87] with description <RBSAssertionDescriptor	 "frontmost:7150" ID:156-87-20502 target:7150 attributes:[
	<RBSDomainAttribute	 domain:"com.apple.launchservicesd" name:"RoleUserInteractiveFocal" sourceEnvironment:"(null)">
	]>
default	22:08:16.420892-0700	runningboardd	Assertion 156-87-20502 (target:app<application.net.runelite.launcher.6564800.6564806(501)>) will be created as active
default	22:08:16.421325-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring jetsam update because this process is not memory-managed
default	22:08:16.421447-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring suspend because this process is not lifecycle managed
default	22:08:16.421545-0700	runningboardd	Finished acquiring assertion 156-87-20502 (target:app<application.net.runelite.launcher.6564800.6564806(501)>)
default	22:08:16.421637-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Set darwin role to: UserInteractiveFocal
default	22:08:16.421823-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring GPU update because this process is not GPU managed
default	22:08:16.421267-0700	runningboardd	Calculated state for app<application.net.runelite.launcher.6564800.6564806(501)>: running-active (role: UserInteractiveFocal)
default	22:08:16.422053-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Skipping AppNap state - not lifecycle managed
default	22:08:16.424334-0700	runningboardd	Acquiring assertion targeting app<application.net.runelite.launcher.6564800.6564806(501)> from originator [daemon<com.apple.coreservices.appleevents(55)>:386] with description <RBSAssertionDescriptor	 "AE/RuneLite" ID:156-386-20503 target:7150 attributes:[
	<RBSDomainAttribute	 domain:"com.apple.launchservicesd" name:"LSNotification" sourceEnvironment:"(null)">
	]>
default	22:08:16.424398-0700	runningboardd	Assertion 156-386-20503 (target:app<application.net.runelite.launcher.6564800.6564806(501)>) will be created as active
default	22:08:16.424711-0700	runningboardd	Calculated state for app<application.net.runelite.launcher.6564800.6564806(501)>: running-active (role: UserInteractiveFocal)
default	22:08:16.424724-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring jetsam update because this process is not memory-managed
default	22:08:16.424818-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring suspend because this process is not lifecycle managed
default	22:08:16.424891-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring GPU update because this process is not GPU managed
default	22:08:16.425046-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Skipping AppNap state - not lifecycle managed
default	22:08:16.425045-0700	runningboardd	Finished acquiring assertion 156-386-20503 (target:app<application.net.runelite.launcher.6564800.6564806(501)>)
default	22:08:21.425014-0700	runningboardd	Assertion did invalidate due to timeout: 156-386-20503 (target:app<application.net.runelite.launcher.6564800.6564806(501)>)
default	22:08:21.624878-0700	runningboardd	Calculated state for app<application.net.runelite.launcher.6564800.6564806(501)>: running-active (role: UserInteractiveFocal)
default	22:08:21.624911-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring jetsam update because this process is not memory-managed
default	22:08:21.624948-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring suspend because this process is not lifecycle managed
default	22:08:21.625201-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Ignoring GPU update because this process is not GPU managed
default	22:08:21.625749-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] Skipping AppNap state - not lifecycle managed
error	22:08:22.419028-0700	kernel	Sandbox: logd_helper(118) deny(1) file-read-data /Applications/RuneLite.app/Contents/Resources/jre/lib/libzip.dylib
error	22:08:22.419250-0700	kernel	Sandbox: logd_helper(118) deny(1) file-read-data /Applications/RuneLite.app/Contents/Resources/jre/lib/libjimage.dylib
error	22:08:22.419483-0700	kernel	Sandbox: logd_helper(118) deny(1) file-read-data /Applications/RuneLite.app/Contents/Resources/jre/lib/libnio.dylib
error	22:08:22.419732-0700	kernel	Sandbox: logd_helper(118) deny(1) file-read-data /Applications/RuneLite.app/Contents/Resources/jre/lib/libnet.dylib
default	22:08:22.419961-0700	loginwindow	-[PersistentAppsSupport applicationQuit:] 	 for app:RuneLite, _appTrackingState = 2
default	22:08:22.419995-0700	loginwindow	-[PersistentAppsSupport applicationQuit:] 	 App: RuneLite, quit, updating active tracking timer
default	22:08:22.420170-0700	runningboardd	Invalidating assertion 156-87-20502 (target:app<application.net.runelite.launcher.6564800.6564806(501)>) from originator [daemon<com.apple.coreservices.launchservicesd>:87]
default	22:08:22.420876-0700	runningboardd	Invalidating assertion 156-87-20490 (target:app<application.net.runelite.launcher.6564800.6564806(501)>) from originator [daemon<com.apple.coreservices.launchservicesd>:87]
default	22:08:22.423820-0700	runningboardd	[app<application.net.runelite.launcher.6564800.6564806(501)>:7150] termination reported by launchd (2, 9, 9)
default	22:08:22.423851-0700	runningboardd	Removing process: [app<application.net.runelite.launcher.6564800.6564806(501)>:7150]
default	22:08:22.424258-0700	runningboardd	Removing launch job for: [app<application.net.runelite.launcher.6564800.6564806(501)>:7150]
default	22:08:22.424557-0700	runningboardd	Removed job for [app<application.net.runelite.launcher.6564800.6564806(501)>:7150]
default	22:08:22.424580-0700	runningboardd	Removing assertions for terminated process: [app<application.net.runelite.launcher.6564800.6564806(501)>:7150]
default	22:08:22.424834-0700	runningboardd	Calculated state for app<application.net.runelite.launcher.6564800.6564806(501)>: none (role: None)
default	22:08:22.430696-0700	runningboardd	Calculated state for app<application.net.runelite.launcher.6564800.6564806(501)>: none (role: None)
default	22:08:22.431497-0700	launchservicesd	Hit the server for a process handle 3080cf9600001bee that resolved to: [app<application.net.runelite.launcher.6564800.6564806(501)>:7150]
error	22:08:22.534514-0700	runningboardd	RBSStateCapture remove item called for untracked item 156-87-20502 (target:app<application.net.runelite.launcher.6564800.6564806(501)>)
error	22:08:22.534562-0700	runningboardd	RBSStateCapture remove item called for untracked item 156-87-20490 (target:app<application.net.runelite.launcher.6564800.6564806(501)>)
`

**Comment by mattmischuk** [comment]
@Broooklyn is there any plans to update the client to use an xcode build with macos features such as a proper OS toolbar window sizer etc.

**Comment by Broooklyn** [comment]
@mattmischuk What do you mean proper OS toolbar window sizer?

**Comment by chadbdurham** [comment]
I assume this would be in reference to getting the minimize, zoom and other options outside of the exit to work on the toolbar. Currently minimize via the toolbar just causes a freeze of the client side.

**Comment by mattmischuk** [comment]
@Broooklyn I just mean using the native APIs available instead of rendering the title bar as a windows clone in Java.
https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/window-anatomy/

**Comment by Broooklyn** [comment]
@mattmischuk That already exists though? Just uncheck `Enable custom window chrome` under `Window Settings` in the `RuneLite` plugin. 
<img width="1043" alt="Screen Shot 2020-07-23 at 11 16 02 AM" src="https://user-images.githubusercontent.com/54762282/88304203-f7759500-ccd5-11ea-99d6-639697ac59e9.png">

**Comment by mattmischuk** [comment]
@Broooklyn fascinating. Would it make sense to make this default for mac users? I think it would, most apps that have custom window chrome (such as Atom and VSCode) have it as a secondary option. I can make a separate issue and PR for that change.

**Comment by robotimer** [comment]
I'd just like to note that as of the latest Big Sur beta release, the terminal workaround is no longer required to open RuneLite.

**Comment by chadbdurham** [comment]
Try launching this as normal now as it's now working for me. 

If someone else can confirm, I will close the issue.

**Comment by AndrewWCarson** [comment]
@chadbdurham I can confirm as well.

**Comment by aronvandepol** [comment]
Works for me too.

**Comment by Adam-** [comment]
We think we tracked down what was causing this, which is fixed in https://github.com/runelite/launcher/commit/27c82f85743b759c8fc46cd752a7c11d2f24a28e. It also happens sometimes on not Big Sur beta 1 but not as often

**Comment by Harrisonlift** [comment]
Seems like the GPU plugin is no longer working on Big Sur Beta 4. When I enable the GPU plugin, my screen either goes black or freezes.

**Comment by ofthesoul** [comment]
> Seems like the GPU plugin is no longer working on Big Sur Beta 4. When I enable the GPU plugin, my screen either goes black or freezes.

Same issue.
Also, not sure if its just because the gpu plugin has to be disabled now (I only have integrated graphics anyway) but the performance on my 2017 13 inch MacBook Pro has suffered greatly on Big Sur beta with runelite. It's almost unplayable. Fps is low (not like 5fps but still not smooth 40+ like it was on Catalina) but its also stuttering pretty often.

**Comment by Harrisonlift** [comment]
I use a 16” MBP with dGPU and it still happens

**Comment by mattmischuk** [comment]
The latest version of Big Sur public beta is causing the RuneLite app to stop loading and display a gray screen after the plugins have been loaded.

**Comment by bheppe** [comment]
is there another work around to this? ^

**Comment by Broooklyn** [comment]
Yeah—Not using beta software

**Comment by mattmischuk** [comment]
@Broooklyn I only use beta software on my secondary laptop for this reason. Building a macOS app right now so I need it 😅

**Comment by Adam-** [comment]
Can anyone who is unable to run the GPU plugin on beta 4 try using the experimental gpu plugin from the pluginhub and let me know if it works?

**Comment by robotimer** [comment]
I am still on Beta 3 (not upgrading because I rely on the GPU plugin) so I can't test that, however I CAN report that the experimental version of the GPU plugin fixes the issues it has with the stretched mode plugin! Previously, the screen would get all resized wrong while using stretched and GPU at the same time.

**Comment by robotimer** [comment]
Nevermind, now it's crashing any time I try to enabled stretched mode with the experimental GPU on.

**Comment by Harrisonlift** [comment]
> Can anyone who is unable to run the GPU plugin on beta 4 try using the experimental gpu plugin from the pluginhub and let me know if it works?

@Adam-  I am on Beta 4, it's working. Only used it for a minute so I'll report back if I encounter any issues. What's different here? Any idea what Apple changed to break the plugin?

**Comment by mmccoy37** [comment]
@Adam- Big Sur has been out for a while now with Runelite working. I can also confirm it works on the Monterey beta. I think this issue can be closed.


<img width="1077" alt="image" src="https://user-images.githubusercontent.com/5104620/124129406-9cded000-da32-11eb-8c97-b644eb295aaf.png">
