### ISSUE TITLE
Java 17 aarch64/MacOS:M1 Fails to Launch RuneLite Client

### ISSUE THREAD

**Issue by IComplainInComments** [runelite/runelite#14139]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
RuneLite client fails to launch after the Loader exits.

**To Reproduce**
Install Java 17 Release Client for macOS aarch64
Double click RuneLite.Jar

**Expected behavior**
RuneLite Client to launch, it fails to after the Launcher closes

**Environment (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - RuneLite version: 1.7.24
 - Launcher version: 2.1.5

**Additional context**
Client.log entry

`2021-09-13 21:41:30 [main] INFO  net.runelite.client.RuneLite - RuneLite 1.7.24 (launcher version 2.1.5) starting up, args: none
2021-09-13 21:41:31 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2021-09-13 21:41:31 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2021-09-13 21:41:31 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1583155852.255
2021-09-13 21:41:31 [main] INFO  n.r.client.account.SessionManager - No session file exists
2021-09-13 21:41:32 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-09-13 21:41:32 [main] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "dance-party" version "b712c124" commit "b712c124b06e791c73339ed21f7ab2ea87fa7ecf"
2021-09-13 21:41:32 [main] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.2" commit "3cc7b618e1a7841bffcdfb0f1c674f11f2c72887"
2021-09-13 21:41:32 [main] ERROR net.runelite.client.RuneLite - Failure during startup
java.lang.reflect.InvocationTargetException: null
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1369)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1344)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at net.runelite.client.ui.ClientUI.init(ClientUI.java:310)
	at net.runelite.client.RuneLite.start(RuneLite.java:311)
	at net.runelite.client.RuneLite.main(RuneLite.java:251)
Caused by: java.lang.IllegalAccessError: class net.runelite.client.util.OSXUtil (in unnamed module @0xc47e05a) cannot access class com.apple.eawt.FullScreenUtilities (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @0xc47e05a
	at net.runelite.client.util.OSXUtil.tryEnableFullscreen(OSXUtil.java:47)
	at net.runelite.client.ui.ClientUI.lambda$init$5(ClientUI.java:325)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`
	
The specific issue causing the Error: Caused by: `java.lang.IllegalAccessError: class net.runelite.client.util.OSXUtil (in unnamed module @0xc47e05a) cannot access class com.apple.eawt.FullScreenUtilities (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @0xc47e05a`

**Comment by Adam-** [comment]
This isn't specific to aarch64 and applies to Java 16+. Most of this is launcher work though and not really related to the client. There is #12959 for the macos aarch64 port which is related but has its own problems independent of Java 16/17.

**Comment by IComplainInComments** [comment]
> This isn't specific to aarch64 and applies to Java 16+. Most of this is launcher work though and not really related to the client. There is #12959 for the macos aarch64 port which is related but has its own problems independent of Java 16/17.

The fix here is to use a third part Java that is JDK 11.

Java 17 is going to be the replacement for Java 11 LST, and offers many features for MacOS users including Native Metal support for graphics. 

Even if this isnt an aarch64 problem, wouldnt it be prudent to fix this issue either way? Since this is specifically for a Java LTS release?

**Comment by Adam-** [comment]
Yes, a lot of this is fixed in fb2bcf9a963a331068a46ac6ce15b7bccc2c8244 and 23f90b5fe4f60246f7cfc3173f9285df0aaca329 in runelite/launcher - but this is unreleased because it is unfinished. I am just pointing out you are identifying two separate issues (macos aarch64 and also jdk 17) - and not trying to argue that neither should be fixed.

**Comment by Adam-** [comment]
And also I think this is not a valid issue since 1) there is an issue already for aarch64 2) the others belong to the launch repo which already has code committed to fix it, so am closing this

**Comment by IComplainInComments** [comment]
> And also I think this is not a valid issue since 1) there is an issue already for aarch64 2) the others belong to the launch repo which already has code committed to fix it, so am closing this

sick bruh 🙄

**Comment by josephalai** [comment]
FYI, this error still persists. However, running RuneLite Client with JDK 11 does apparently resolve this for me. Using macOS Monterey 12.5, 3.6 GHz 10-Core Intel Core i9.
