### ISSUE TITLE
Holding down key on Mac makes it impossible to type in client.

### ISSUE THREAD

**Issue by JSturge** [runelite/runelite#3514]
Normally, when you hold down a key on Mac, if available, an accented characters menu pops up. However, when you hold a key, such as "o", it makes it impossible to type in the client afterwards.

Refer to the Type accented characters section for more information about special characters:
https://support.apple.com/en-us/HT201586

**Comment by Nightfirecat** [comment]
Does the vanilla client have the same behavior?

**Comment by JSturge** [comment]
Yes actually, good catch.

**Comment by bryandh** [comment]
The `alt` key does seem to continue working, probably as it's something handled by RuneLite itself (hidden loot display).
If I recall correctly, the `shift` key drop modifier *does* seem to continue working.
It just doesn't seem possible to type anything, or use arrow keys for camera movement, at all.

**Comment by Zirro** [comment]
I have attempted to reproduce this on the latest 10.15/Catalina beta with both RuneLite and the official client, but I'm not seeing the issue experienced by OP. When holding down keys while typing inside the game, the menu does not pop-up at all and I'm able to continue typing as usual. Outside the game in the search field of the RuneLite sidebar, the pop-up menu appears as expected and does not prevent further typing.

This might be something that has been fixed in Catalina, or it could merely be something specific to my settings. I'm not able to test on Mojave or older OS versions at this time.

@JSturge @bryandh @dappersnapper456 @jpseeley
If any of you are currently using the Catalina beta, it'd be great if you could check whether this has been resolved for you. Otherwise it might be fixable by setting `ApplePressAndHoldEnabled` to false in the RuneLite launcher, which would prevent the menu from appearing anywhere in the application.

**Comment by TylerADavis** [comment]
@Zirro I'm also unable to reproduce on 10.15.3

**Comment by forrestwilkins** [comment]
Was there ever a fix for this issue? I'm still seeing it happen on MacOS Sonoma 14.0.
