### ISSUE TITLE
Ctrl-F11 hotkey does not hide sidebar when sidebar has focus

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#5009]
Not sure if this is intentional or not, my guess would be not.

Possibly related to Issue #4945 / PR #4990

**Comment by Abextm** [comment]
#4945 & #4990 have nothing to do with this, it is simply that the listener is only bound on the gameframe

**Comment by rbbi** [comment]
@ShaunDreclin Can you confirm this was fixed by #4990 ?

**Comment by deathbeam** [comment]
Dont think so, this is different issue as @Abextm said

**Comment by ShaunDreclin** [comment]
@rbbi yep not fixed, issues weren't related.

**Comment by Gamer1120** [comment]
This issue is still present, and also the case when custom window chrome is disabled and the title bar is clicked: https://www.youtube.com/watch?v=EfIBAEhWnLU&feature=youtu.be

**Comment by deathbeam** [comment]
Yeah, I don't think this is fixable, or it makes sense to "fix" it, because then we would need to add listeners to like input fields and that is probably wrong (because, only sidebars that have input fields make this not work, like config panel and hiscore panel, that grab focus to text field when you open them).
