### ISSUE TITLE
Runelite client mini freeze every 5-10 seconds

### ISSUE THREAD

**Issue by LuukvanDriel** [runelite/runelite#8187]
**Describe the bug**
Just recently, I  have been experiencing periodic freezes in the Runelite client. When playing, from the moment I log in, approximately every 5-15 seconds, everything in the game (movement, chat etc) will freeze for about half a second. This process keeps repeating itself indefinetely, which hinders a smooth and enjoyable gameplay. 

- I am not running compactability mode.

-  I have tried disabling hardware accelaration

- I have checked the FPS, which remain stable.

- I have checked multiple internet connections (wired, wifi 2.4Ghz , wifi 5.0Ghz, 4g hotspot) 

**To Reproduce**
1. Just launching the client and playing

**Expected behavior**
No periodic freezes, but just smooth gameplay.

**Environment 
 - OS: Windows 10
 - RuneLite version: 1.5.15.1
 - Launcher version: 1.6.0

**Additional context**
[client.log](https://github.com/runelite/runelite/files/2957016/client.log)
[launcher.log](https://github.com/runelite/runelite/files/2957021/launcher.log)

**Comment by deathbeam** [comment]
This is probably just garbage collector, i saw some people go over our set limits

**Comment by TheDuckChris** [comment]
This is happening to me too, on and off. Not as frequent as every 10 seconds, more like every few minutes for me. Not sure what "garbage collector" means so if it's something we can fix please detail.

**Comment by Nightfirecat** [comment]
This is likely due to Java GC, which should have been addressed when we updated the launcher to use Java 11. (see #9329)

**Comment by Nealon01** [comment]
This has begun happening to me over the last couple months.  However, they symptoms are a little different.  My FPS tanks when it happens even though my CPU and GPU are pretty much idle (runelite usage hovers around 10-15% for both).  I generally use GPU rendering and animation smoothing but confirmed that it still happens with both disabled as well.

I've rebooted and reinstalled runelite several times and the issue persists.  The rest of my system remains responsive when it happens, and it doesn't happen in any application other than runelite.

**Comment by MESLewis** [comment]
Join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.

**Comment by Nealon01** [comment]
After joining the discord, it was discovered that an old "fake" version of runelite I had installed a couple years ago to see what different plugins it had (before runelite's plugin hub) was likely causing the issue.  After getting lectured on why I should never install anything other than runelite, it was suggested that I uninstall everything runelite related, and delete the .runelite directory, and then try reinstalling.

Only been running for a bit since doing that, but the issue appears to be gone now.  Thank the lord.
